# Generated by Django 2.1.7 on 2019-03-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwner_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.IntegerField(default='09036878432', max_length=11)),
                ('Figi_ID', models.IntegerField(blank=True)),
                ('Bvn', models.IntegerField(max_length=11)),
                ('CAC_certificate', models.FileField(upload_to='Documents/')),
                ('Affidavit', models.FileField(upload_to='Documents/')),
                ('Guarrantor1_Email', models.CharField(default='Gurrantor Email', max_length=50)),
                ('Guarrantor1_Phone_Number', models.IntegerField(default='09032421311', max_length=11)),
                ('Guarrantor2_Email', models.CharField(default='Gurrantor Email', max_length=50)),
                ('Guarrantor2_Phone_Number', models.IntegerField(default='09032421311', max_length=11)),
                ('Present_Stage_of_Business', models.CharField(choices=[('Idea', 'Idea'), ('Market-Testing', 'Market-Testing'), ('Deployed', 'Deployed')], max_length=50)),
                ('Passport_Photograph', models.FileField(upload_to='Documents')),
                ('Business_Statement', models.TextField(default='Tell us about your Business')),
                ('Business_Video', models.FileField(upload_to='videos')),
                ('Name_of_Business', models.CharField(default='Business Name', max_length=50)),
                ('Industry_of_Business', models.CharField(choices=[('Trading', 'Trading'), ('ICT', 'ICT'), ('Real Estate', 'Real Estate')], max_length=50)),
                ('Address_of_Business', models.TextField(default='Business Address', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Investor_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_fullname', models.CharField(default='Jon Samuel', max_length=50, null='True')),
                ('Address', models.CharField(default='Resendential Address', max_length=100)),
                ('Age', models.IntegerField(default=12)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('Figi_Username', models.CharField(blank=True, default='Figi Username', max_length=50)),
                ('Next_of_Kin', models.CharField(default='Next of kin Name', max_length=50)),
                ('Next_of_Kin_Address', models.CharField(default='Address of Next of kin', max_length=100)),
                ('Bank_Name', models.CharField(default='GTB', max_length=50)),
                ('Bank_Type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=50)),
                ('Account_Number', models.IntegerField(default='2091047681', max_length=10)),
                ('Bvn', models.IntegerField(help_text='Enter your bank BVN', max_length=11)),
            ],
        ),
    ]
