# Generated by Django 2.1.7 on 2019-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0002_businessowner_registration_investor_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner_registration',
            name='Percent',
            field=models.IntegerField(default=5, help_text='How much percent are you willing to give'),
        ),
        migrations.AddField(
            model_name='investor_registration',
            name='Amount',
            field=models.IntegerField(default=200000),
        ),
        migrations.AddField(
            model_name='investor_registration',
            name='Time_Period',
            field=models.CharField(choices=[('12months', '12months'), ('18months', '18months'), ('24months', '24months'), ('36months', '36months'), ('60months', '60months')], default='6months', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Bvn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Guarrantor1_Phone_Number',
            field=models.IntegerField(default='09032421311'),
        ),
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Guarrantor2_Phone_Number',
            field=models.IntegerField(default='09032421311'),
        ),
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Phone_Number',
            field=models.IntegerField(default='09036878432'),
        ),
        migrations.AlterField(
            model_name='investor_registration',
            name='Account_Number',
            field=models.IntegerField(default='2091047681'),
        ),
        migrations.AlterField(
            model_name='investor_registration',
            name='Address',
            field=models.TextField(default='Resendential Address'),
        ),
        migrations.AlterField(
            model_name='investor_registration',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='investor_registration',
            name='Bvn',
            field=models.IntegerField(help_text='Enter your bank BVN'),
        ),
        migrations.AlterField(
            model_name='investor_registration',
            name='Next_of_Kin_Address',
            field=models.TextField(default='Address of Next of kin', max_length=100),
        ),
    ]
