# Generated by Django 2.1.7 on 2019-03-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0003_auto_20190319_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+234', help_text='Field to save the phone number of the user.', max_length=15, unique=True, verbose_name='phone number'),
        ),
    ]
