# Generated by Django 2.1.7 on 2019-03-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0005_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Category',
            field=models.CharField(choices=[('Investor', 'Investor'), ('Business Owner', 'Business Owner')], default='Investor', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20),
            preserve_default=False,
        ),
    ]
