# Generated by Django 2.1.7 on 2019-03-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0006_auto_20190326_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Affidavit',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Business_Video',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='businessowner_registration',
            name='CAC_certificate',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Passport_Photograph',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Phone_Number',
            field=models.IntegerField(default='09036878432', unique=True),
        ),
    ]
