# Generated by Django 2.1.7 on 2019-03-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0007_auto_20190328_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_filledform',
            field=models.BooleanField(default=False),
        ),
    ]
