# Generated by Django 2.1.7 on 2019-03-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0008_user_has_filledform'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner_registration',
            name='Business_Image',
            field=models.ImageField(default='/home/david/miniconda3/hedge2/media/media/vuy8fi0p0vd21.jpg', upload_to='media/'),
            preserve_default=False,
        ),
    ]
