# Generated by Django 2.1.7 on 2019-03-30 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0009_businessowner_registration_business_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner_registration',
            name='owner',
            field=models.ForeignKey(default='deveid', on_delete=django.db.models.deletion.CASCADE, related_name='businessowner_registration', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
