# Generated by Django 2.1.7 on 2019-03-30 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0010_businessowner_registration_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner_registration',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businessowner_registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
