# Generated by Django 2.1.7 on 2019-03-30 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0011_auto_20190330_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner_registration',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
