# Generated by Django 2.1.7 on 2019-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0012_auto_20190330_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Percent',
            field=models.FloatField(default=5, help_text='How much percent are you willing to give'),
        ),
    ]
