# Generated by Django 2.1.7 on 2019-04-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0013_auto_20190401_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner_registration',
            name='verifyDocument',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Business_Video',
            field=models.FileField(help_text='Video size should not be more than 2MB', upload_to='media'),
        ),
    ]
