# Generated by Django 2.1.7 on 2019-04-04 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0014_auto_20190402_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='investor_registration',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nittan.Investor_Registration'),
        ),
        migrations.AddField(
            model_name='payment',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nittan.BusinessOwner_Registration'),
        ),
    ]
