# Generated by Django 2.1.7 on 2019-04-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0015_auto_20190404_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='word',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='item',
            new_name='paid_investor',
        ),
    ]
