# Generated by Django 2.1.7 on 2019-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0016_auto_20190404_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Amount',
            field=models.IntegerField(default=2000000),
        ),
    ]
