# Generated by Django 2.1.7 on 2019-04-04 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0017_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
