# Generated by Django 2.1.7 on 2019-04-04 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0018_payment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='owner',
            field=models.ForeignKey(default='Nil', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
