# Generated by Django 2.1.7 on 2019-04-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0019_auto_20190404_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='owner',
        ),
    ]
