# Generated by Django 2.1.7 on 2019-04-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0020_remove_payment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid_investor',
            new_name='paidInvestor',
        ),
    ]
