# Generated by Django 2.1.7 on 2019-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0021_auto_20190404_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor_registration',
            name='Time_Period',
        ),
        migrations.AddField(
            model_name='businessowner_registration',
            name='Time_Period',
            field=models.CharField(choices=[('12months', '12months'), ('18months', '18months'), ('24months', '24months'), ('36months', '36months'), ('60months', '60months')], default='6months', max_length=50),
        ),
    ]
