# Generated by Django 2.1.7 on 2019-04-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0022_auto_20190415_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Time_Period',
            field=models.IntegerField(default=1, help_text='Time Period of Investment', max_length=50),
        ),
    ]
