# Generated by Django 2.1.7 on 2019-04-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0023_auto_20190415_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Time_Period',
            field=models.IntegerField(default=6, help_text='Time Period of Investment in months'),
        ),
    ]
