# Generated by Django 2.1.7 on 2019-04-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0025_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
