# Generated by Django 2.1.7 on 2019-04-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0027_auto_20190420_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='payments',
        ),
    ]
