# Generated by Django 2.1.7 on 2019-04-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0029_auto_20190423_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor_registration',
            old_name='Amount',
            new_name='Investment',
        ),
        migrations.AddField(
            model_name='investor_registration',
            name='Earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investor_registration',
            name='investedCompanyName',
            field=models.CharField(default='None', max_length=90000000000000000),
        ),
        migrations.AddField(
            model_name='investor_registration',
            name='noOfCompanyInvested',
            field=models.IntegerField(default=0),
        ),
    ]
