# Generated by Django 2.1.7 on 2019-04-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0031_auto_20190423_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessowner_registration',
            old_name='Investor',
            new_name='InvestorName',
        ),
    ]
