# Generated by Django 2.1.7 on 2019-04-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0032_auto_20190424_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner_registration',
            name='Investment',
            field=models.CharField(default=0, max_length=90000000000000000000000000000000),
        ),
    ]
