# Generated by Django 2.1.7 on 2019-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0035_auto_20190424_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='Bank_Teller',
            field=models.ImageField(default='/home/david/miniconda3/hedge2/media/media/1.jpg', upload_to='media/'),
        ),
    ]
