# Generated by Django 2.1.7 on 2019-04-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0036_auto_20190424_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='Bank_Teller',
            field=models.ImageField(default='/no Image Uploaded', upload_to='media/'),
        ),
    ]
