# Generated by Django 2.1.7 on 2019-04-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nittan', '0039_contactmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='expectedEarning',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.CharField(max_length=9000000000000000000000000),
        ),
    ]
